api:
  replicaCount: 2
  image:
    repository: ghcr.io/milen-donchev/kinti-api
    tag: latest
    pullPolicy: IfNotPresent

web:
  replicaCount: 2
  image:
    repository: ghcr.io/milen-donchev/kinti-web
    tag: latest
    pullPolicy: IfNotPresent

ingress:
  className: traefik
  host: 46.101.230.169.sslip.io

imagePullSecrets:
  - name: ghcr-pull-secret
