api:
  replicaCount: 2
  image:
    repository: ghcr.io/milen-donchev/kinti-api
    tag: ""
    pullPolicy: IfNotPresent
  config:
    NODE_ENV: production
    SUPABASE_URL: https://auzgqefookfzxmbejpjx.supabase.co
    SUPABASE_JWT_ISSUER: https://auzgqefookfzxmbejpjx.supabase.co/auth/v1
    WEB_ORIGIN: https://levko.bg

web:
  replicaCount: 2
  image:
    repository: ghcr.io/milen-donchev/kinti-web
    tag: ""
    pullPolicy: IfNotPresent
  config:
    VITE_API_URL: https://levko.bg/api
    VITE_SUPABASE_URL: https://auzgqefookfzxmbejpjx.supabase.co

ingress:
  className: traefik
  host: levko.bg
  hosts:
    - levko.bg
    - www.levko.bg
  tls:
    enabled: true
    secretName: levko-bg-tls
    clusterIssuer: letsencrypt-prod

imagePullSecrets:
  - name: ghcr-pull-secret
