apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.api.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
