apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "api.secrets.DATABASE_URL is required" .Values.api.secrets.DATABASE_URL | quote }}
  DIRECT_URL: {{ required "api.secrets.DIRECT_URL is required" .Values.api.secrets.DIRECT_URL | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ required "api.secrets.SUPABASE_SERVICE_ROLE_KEY is required" .Values.api.secrets.SUPABASE_SERVICE_ROLE_KEY | quote }}
