apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.web.name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  VITE_SUPABASE_ANON_KEY: {{ required "web.secrets.VITE_SUPABASE_ANON_KEY is required" .Values.web.secrets.VITE_SUPABASE_ANON_KEY | quote }}
