apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  revisionHistoryLimit: {{ .Values.web.deployment.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.web.deployment.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.web.deployment.strategy.maxSurge }}
      maxUnavailable: {{ .Values.web.deployment.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
    {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ required "web.image.tag is required" .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.web.name }}-config
            - secretRef:
                name: {{ .Values.web.name }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.web.probes.readiness.path }}
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: {{ .Values.web.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.probes.liveness.path }}
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: {{ .Values.web.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.liveness.periodSeconds }}
          resources:
{{- toYaml .Values.web.resources | nindent 12 }}
